spring:
  profiles:
    include: datasource
  application:
    name: ${APPLICATION_NAME}

server:
  servlet:
    context-path: /api
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_MILLIS:3600000}

job:
  enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.web.authentication: DEBUG
        security.web.access: DEBUG
